load("@rules_grafana//grafana:grafana.bzl", "json_dashboards", "py_dashboards")
load("@rules_grafana//grafana:image.bzl", "grafana_image")
load("@rules_oci//oci:defs.bzl", "oci_load")

# Picks up all *.json files in this directory:
json_dashboards(
    name = "json_dashboards",
    srcs = glob(["*.json"], allow_empty = True),
)

# Picks up all *.py files in this directory:
py_dashboards(
    name = "py_dashboards",
    srcs = glob(["*.py"], allow_empty = True),
)

# Built dashboards can be combined together in a filegroup for easy access:
filegroup(
    name = "dashboards",
    srcs = [
        ":json_dashboards",
        ":py_dashboards",
    ],
    visibility = ["//visibility:public"],
)

# Build the dashboards into a docker image:
grafana_image(
    name = "grafana",
    dashboards = [":dashboards"],
    datasources = [":datasources.yaml"],
)

# Load the Grafana image into Docker for local testing:
oci_load(
    name = "grafana_load",
    image = ":grafana",
    repo_tags = ["rules_grafana/example:latest"],
)
